global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: otel-agent
    static_configs:
      - targets: ["otel-agent:8888"]

  - job_name: otel-gateway
    static_configs:
      - targets: ["otel-gateway:8888"]

  - job_name: otel-consumer
    static_configs:
      - targets: ["otel-consumer:8888"]
